name: Package application

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: TonyPacker

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: TonyPacker/dist/windows
